package programacion1.Videojuego;

import java.util.ArrayList;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
    private int contcontra=0,contusuario=0;
    private String contra; 
    private String usuario;
    boolean mododejuego_Tutorial=true;
   ArrayList<Loggs> ListadeLoggs;
//las variables globales siempre son arriba del public nombre(nombre de la clase) y debajo del public class    
ArrayList<Usuario> ListadeUsuarios;
    
 public Login(ArrayList<Usuario> AtributListadeUsuarios,ArrayList<Loggs> AtributListadeLoggs,boolean mododejuego) {
        //el atributo es la variable en la que se guarda los valores de cada clase en la variable global
      if(AtributListadeUsuarios==null){
        ListadeUsuarios = new ArrayList<Usuario>();
          System.out.println("se crea nuevo");
        }else{
      
            
            System.out.println("acepta atributo");
            ListadeUsuarios=AtributListadeUsuarios; 
            
        }
        
       if ( AtributListadeLoggs== null) {
            ListadeLoggs = new ArrayList<Loggs>();

        } else {

            ListadeLoggs  = AtributListadeLoggs;

        }   
        mododejuego_Tutorial=mododejuego;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barrausuario = new javax.swing.JTextField();
        barracontraseña = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setForeground(new java.awt.Color(153, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Luminari", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 165, 60));

        barrausuario.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        barrausuario.setText("Ingrese su Nombre");
        barrausuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barrausuarioMouseClicked(evt);
            }
        });
        barrausuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barrausuarioActionPerformed(evt);
            }
        });
        jPanel1.add(barrausuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 300, 40));

        barracontraseña.setText("jPasswordField1");
        barracontraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barracontraseñaMouseClicked(evt);
            }
        });
        barracontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barracontraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(barracontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 300, 40));

        jButton1.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jButton2.setFont(new java.awt.Font("Luminari", 0, 13)); // NOI18N
        jButton2.setText("Crear Player");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programacion1/Videojuego/Imagenes/Configuracion/1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        CrearPlayer Cp=new CrearPlayer(ListadeUsuarios,this.ListadeLoggs,mododejuego_Tutorial);
        this.setVisible(false);
        Cp.setVisible(true);

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        //el for busca la concidencia con un usuario porque el array tiene dos valores
        int posicion=-1;
     
        for(int i=0;i<ListadeUsuarios.size();i++){
            System.out.println(ListadeUsuarios.get(i).getnombre());
            if(ListadeUsuarios.get(i).getnombre().equals(barrausuario.getText())){

                posicion=i;

            }

        }

        System.out.println(
            posicion);

        //Validacion de existencia de usuario

        if(posicion!=-1){

       

            //aqui le estamos diciendo que en esa posicion nos verifica la contraseña
            if( ListadeUsuarios.get(posicion).getcontra().equals(barracontraseña.getText())  ){

                System.out.println("correcto");
                JOptionPane.showMessageDialog(null,"Inicializo Correctamente");
                MenuPrincipal Mp=new MenuPrincipal(this.ListadeUsuarios,this.ListadeLoggs,barrausuario.getText(),mododejuego_Tutorial);
                Mp.setVisible(true);
                this.setVisible(false);

            }else{

                JOptionPane.showMessageDialog(null,"Contraseña Incorrecta");
            }

        }else{

            System.out.println("incorrecto");
            JOptionPane.showMessageDialog(null,"Usuario no existe");

        }

        //Validacion de que el nombre y la contraseña concuerden

    }//GEN-LAST:event_jButton1MouseClicked

    private void barracontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barracontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barracontraseñaActionPerformed

    private void barrausuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barrausuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barrausuarioActionPerformed

    private void barrausuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barrausuarioMouseClicked


       if(this.contusuario==0){
       barrausuario.setText("");
       contusuario=1;
       
       }
       
       
       
       
       
       
       
       
    }//GEN-LAST:event_barrausuarioMouseClicked

    private void barracontraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barracontraseñaMouseClicked
      
        //aqui
        
        if(contcontra==0){
         barracontraseña.setText("");
         contcontra=1;   
            
        }
        
        
        
        
    }//GEN-LAST:event_barracontraseñaMouseClicked

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login(null,null,true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField barracontraseña;
    private javax.swing.JTextField barrausuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
